services:
  db:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    container_name: giki_wallet_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - giki_wallet_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giki -d giki_wallet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: giki_wallet_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT:-8080}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - DB_URL=${DB_URL}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

volumes:
  giki_wallet_data: